// app/components/ui/Preloader.vue
<script setup lang="ts">
const pub = usePublicPath();

const PRELOADER_IMAGES = [
    pub('/v2/preloader-icon-1.svg'),
    pub('/v2/preloader-icon-2.svg'),
    pub('/v2/preloader-icon-3.svg'),
];
const STEP_INTERVAL_MS = 500;
// совпадает с transition в preloader.css: прелоадер успевает целиком уехать вверх
const HIDE_ANIMATION_MS = 600;
const OVERFLOW_RESTORE_DELAY_MS = 500;
// Прелоадер держится, пока видео первого экрана не скачается целиком,
// но не дольше этого времени на совсем медленном интернете.
const MAX_WAIT_MS = 20000;
// Минимальное время показа, чтобы прелоадер не мигал, когда видео уже в кэше.
const MIN_SHOW_MS = 1200;
// Первая часть видео первого экрана; вторая (общий план) короткая и догружается следом.
const HERO_VIDEOS = [{ id: 'main-video-banner', weight: 1 }];

const isVisible = ref(true);
const isAnimating = ref(false);
const activeStep = ref(0);
const pageLoadProgress = ref(0);
const isTimedOut = ref(false);
const isMinShown = ref(false);

// Ждём только видео первого экрана: остальные грузятся при прокрутке.
const heroVideoProgress = useVideoLoadingProgress(HERO_VIDEOS);

const combinedProgress = computed(() => isTimedOut.value ? 100 : Math.min(
    Math.round((heroVideoProgress.value * 0.8) + (pageLoadProgress.value * 0.2)),
    100,
));

useLockScroll(isVisible, OVERFLOW_RESTORE_DELAY_MS);

const cleanups: (() => void)[] = [];
onBeforeUnmount(() => cleanups.forEach((fn) => fn()));

onMounted(() => {
    const timer = setTimeout(() => { isTimedOut.value = true; }, MAX_WAIT_MS);
    const minTimer = setTimeout(() => { isMinShown.value = true; }, MIN_SHOW_MS);
    const stepInterval = setInterval(() => {
        activeStep.value = (activeStep.value + 1) % PRELOADER_IMAGES.length;
    }, STEP_INTERVAL_MS);
    cleanups.push(() => {
        clearTimeout(timer);
        clearTimeout(minTimer);
        clearInterval(stepInterval);
    });

    const setPageProgress = (value: number) => {
        pageLoadProgress.value = Math.max(pageLoadProgress.value, value);
    };

    if (document.readyState === 'complete') {
        pageLoadProgress.value = 100;
        return;
    }

    const updatePageLoadProgress = () => {
        const resources = performance.getEntriesByType('resource') as PerformanceResourceTiming[];

        if (resources.length === 0) {
            pageLoadProgress.value = document.readyState === 'loading' ? 10 : 50;
            return;
        }

        const loadedResources = resources.filter(entry => (
            entry.name.includes('.js') ||
            entry.name.includes('.css') ||
            entry.initiatorType === 'script' ||
            entry.initiatorType === 'link' ||
            entry.initiatorType === 'xmlhttprequest' ||
            entry.initiatorType === 'fetch'
        ));

        if (loadedResources.length === 0) {
            pageLoadProgress.value = 50;
            return;
        }

        const totalProgress = loadedResources.reduce((sum, resource) => {
            if (resource.transferSize === 0 && resource.decodedBodySize === 0) {
                return sum + 100;
            }
            return sum + (resource.transferSize ? 100 : 0);
        }, 0);

        setPageProgress(Math.min(Math.round(totalProgress / loadedResources.length), 100));
    };

    updatePageLoadProgress();

    const handleLoad = () => { pageLoadProgress.value = 100; };
    const handleDOMContentLoaded = () => setPageProgress(70);

    let performanceObserver: PerformanceObserver | null = null;
    try {
        performanceObserver = new PerformanceObserver((list) => {
            if (list.getEntries().length > 0) updatePageLoadProgress();
        });
        performanceObserver.observe({ type: 'resource', buffered: true });
    } catch {
        console.warn('PerformanceObserver not supported, using fallback');
    }

    window.addEventListener('load', handleLoad);
    document.addEventListener('DOMContentLoaded', handleDOMContentLoaded);
    const interval = setInterval(updatePageLoadProgress, 200);

    cleanups.push(() => {
        window.removeEventListener('load', handleLoad);
        document.removeEventListener('DOMContentLoaded', handleDOMContentLoaded);
        performanceObserver?.disconnect();
        clearInterval(interval);
    });
});

let hideTimer: ReturnType<typeof setTimeout> | undefined;
cleanups.push(() => clearTimeout(hideTimer));

watch([combinedProgress, isMinShown], ([progress, minShown]) => {
    if (progress < 100 || !minShown || isAnimating.value) return;

    isAnimating.value = true;
    // Первый экран показывает контент, пока прелоадер уезжает вверх
    window.__preloaderHidden = true;
    window.dispatchEvent(new Event(PRELOADER_HIDE_EVENT));

    hideTimer = setTimeout(() => {
        window.scrollTo(0, 0);
        isVisible.value = false;
    }, HIDE_ANIMATION_MS);
});
</script>

<template>
    <div v-if="isVisible" :class="['preloader', { 'preloader--hidden': isAnimating }]">
        <div class="preloader__content">
            <div class="preloader__images">
                <img
                    v-for="(src, index) in PRELOADER_IMAGES"
                    :key="index"
                    :src="src"
                    :alt="`preloader step ${index + 1}`"
                    width="280"
                    height="80"
                    :class="['preloader__image', { 'preloader__image--active': activeStep === index }]"
                >
            </div>

            <div :class="['preloader__progress', FONT_IBM_PLEX_SERIF_LIGHT]">{{ combinedProgress }}%</div>
        </div>
    </div>
</template>

// src/app/components/preloader/preloader.tsx
/* eslint-disable react-hooks/set-state-in-effect */
'use client';

import { useEffect, useRef, useState } from 'react';
import './preloader.css';
import { FONT_IBM_PLEX_SERIF_LIGHT } from '@/app/fonts';
import Image from 'next/image';
import PreloaderImg1 from '../../../../public/v2/preloader-icon-1.svg'
import PreloaderImg2 from '../../../../public/v2/preloader-icon-2.svg'
import PreloaderImg3 from '../../../../public/v2/preloader-icon-3.svg'
import { useVideoLoadingProgress } from '@/app/hooks/use-video-loading-process';
import { PRELOADER_HIDE_EVENT } from '@/app/constants';

declare global {
    interface Window {
        __preloaderHidden?: boolean;
    }
}

const PRELOADER_IMAGES = [PreloaderImg1, PreloaderImg2, PreloaderImg3];
const STEP_INTERVAL_MS = 500;
// совпадает с transition в preloader.css: прелоадер успевает целиком уехать вверх
const HIDE_ANIMATION_MS = 600;
const OVERFLOW_RESTORE_DELAY_MS = 500;
// Прелоадер держится, пока видео первого экрана не скачается целиком,
// но не дольше этого времени на совсем медленном интернете.
const MAX_WAIT_MS = 20000;
// Минимальное время показа, чтобы прелоадер не мигал, когда видео уже в кэше.
const MIN_SHOW_MS = 1200;
// Первая часть видео первого экрана; вторая (общий план) короткая и догружается следом.
const HERO_VIDEOS = [{ id: 'main-video-banner', weight: 1 }];

export const Preloader = () => {
    const [isVisible, setVisible] = useState(true);
    const [isAnimating, setIsAnimating] = useState(false);
    const [activeStep, setActiveStep] = useState(0);
    const [pageLoadProgress, setPageLoadProgress] = useState(0);

    const overflowTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    const [isTimedOut, setTimedOut] = useState(false);
    const [isMinShown, setMinShown] = useState(false);

    // Ждём только видео первого экрана: остальные грузятся при прокрутке.
    const heroVideoProgress = useVideoLoadingProgress(HERO_VIDEOS);

    const combinedProgress = isTimedOut ? 100 : Math.min(
        Math.round((heroVideoProgress * 0.8) + (pageLoadProgress * 0.2)),
        100
    );

    useEffect(() => {
        const timer = setTimeout(() => setTimedOut(true), MAX_WAIT_MS);
        const minTimer = setTimeout(() => setMinShown(true), MIN_SHOW_MS);
        return () => {
            clearTimeout(timer);
            clearTimeout(minTimer);
        };
    }, []);

    useEffect(() => {
        if (document.readyState === 'complete') {
            setPageLoadProgress(100);
            return;
        }

        const updatePageLoadProgress = () => {
            const resources = performance.getEntriesByType('resource') as PerformanceResourceTiming[];
            
            if (resources.length === 0) {
                setPageLoadProgress(document.readyState === 'loading' ? 10 : 50);
                return;
            }

            const loadedResources = resources.filter(entry => {
                return (
                    entry.name.includes('.js') ||
                    entry.name.includes('.css') ||
                    entry.initiatorType === 'script' ||
                    entry.initiatorType === 'link' ||
                    entry.initiatorType === 'xmlhttprequest' ||
                    entry.initiatorType === 'fetch'
                );
            });

            if (loadedResources.length === 0) {
                setPageLoadProgress(50);
                return;
            }

            const totalProgress = loadedResources.reduce((sum, resource) => {
                if (resource.transferSize === 0 && resource.decodedBodySize === 0) {
                    return sum + 100;
                }
                return sum + (resource.transferSize ? 100 : 0);
            }, 0);

            const avgProgress = Math.round(totalProgress / loadedResources.length);
            setPageLoadProgress(prev => Math.max(prev, Math.min(avgProgress, 100)));
        };

        updatePageLoadProgress();

        const handleLoad = () => {
            setPageLoadProgress(100);
        };

        const handleResourceLoad = () => {
            updatePageLoadProgress();
        };

        let performanceObserver: PerformanceObserver | null = null;
        
        try {
            performanceObserver = new PerformanceObserver((list) => {
                const entries = list.getEntries();
                if (entries.length > 0) {
                    updatePageLoadProgress();
                }
            });

            performanceObserver.observe({ type: 'resource', buffered: true });
        } catch {
            console.warn('PerformanceObserver not supported, using fallback');
        }

        window.addEventListener('load', handleLoad);
        
        const interval = setInterval(updatePageLoadProgress, 200);

        const handleDOMContentLoaded = () => {
            setPageLoadProgress(prev => Math.max(prev, 70));
        };
        
        document.addEventListener('DOMContentLoaded', handleDOMContentLoaded);

        return () => {
            window.removeEventListener('load', handleLoad);
            document.removeEventListener('DOMContentLoaded', handleDOMContentLoaded);
            if (performanceObserver) {
                performanceObserver.disconnect();
            }
            clearInterval(interval);
        };
    }, []);

    // Управление overflow с задержкой при скрытии
    useEffect(() => {
        const html = document.documentElement;
        const body = document.body;

        if (overflowTimerRef.current) {
            clearTimeout(overflowTimerRef.current);
        }

        if (isVisible) {
            html.style.overflowY = 'hidden';
            body.style.overflowY = 'hidden';
        } else {
            overflowTimerRef.current = setTimeout(() => {
                html.style.overflowY = '';
                body.style.overflowY = '';
            }, OVERFLOW_RESTORE_DELAY_MS);
        }

        return () => {
            if (overflowTimerRef.current) {
                clearTimeout(overflowTimerRef.current);
            }
            html.style.overflowY = '';
            body.style.overflowY = '';
        };
    }, [isVisible]);

    useEffect(() => {
        const interval = setInterval(() => {
            setActiveStep((prev) => (prev + 1) % PRELOADER_IMAGES.length);
        }, STEP_INTERVAL_MS);

        return () => clearInterval(interval);
    }, []);

    useEffect(() => {
        if (combinedProgress < 100 || !isMinShown) return;

        setIsAnimating(true);
        // Первый экран показывает контент, пока прелоадер уезжает вверх
        window.__preloaderHidden = true;
        window.dispatchEvent(new Event(PRELOADER_HIDE_EVENT));

        const timer = setTimeout(() => {
            window.scrollTo(0,0);
            setVisible(false);
        }, HIDE_ANIMATION_MS);

        return () => clearTimeout(timer);
    }, [combinedProgress, isMinShown]);

    if (!isVisible) {
        return null;
    }

    return (
        <div className={`preloader ${isAnimating ? 'preloader--hidden' : ''}`}>
            <div className="preloader__content">
                <div className="preloader__images">
                    {PRELOADER_IMAGES.map((src, index) => (
                        <Image
                            key={index}
                            src={src}
                            alt={`preloader step ${index + 1}`}
                            width={280}
                            height={80}
                            className={`preloader__image ${activeStep === index ? 'preloader__image--active' : ''}`}
                            unoptimized
                        />
                    ))}
                </div>

                <div className={`preloader__progress ${FONT_IBM_PLEX_SERIF_LIGHT.className}`}>
                    {combinedProgress}%
                </div>
            </div>
        </div>
    );
};
