// src/app/blocks/infinity-banner/infinity-banner.tsx
'use client';

import Image from 'next/image';
import { useRef, useEffect } from 'react';
import TelegaIcon from '../../../../public/v2/infinity-banner-tg.svg';
import LogoWhite from '../../../../public/v2/header-logo-white.svg';

import './infinity-banner.css';
import { FONT_MONT_BOOK } from '@/app/fonts';
import { TELEGRAM_CHANELL_LINK } from '@/app/constants';
import { useGetLinkWithUtm } from '@/app/hooks/use-get-link-with-utm';

const Item = () => (
  <div className="infinity-banner-item">
    <Image src={TelegaIcon} alt="telegramm-icon" height={36} width={36}
      className="infinity-banner-tg" unoptimized />
    <Image src={LogoWhite} alt="southuub" width={220} height={24}
      className="infinity-banner-logo" unoptimized />
    <p className={`${FONT_MONT_BOOK.className} infinity-banner-text`}>
      Все инсайты и новости ближе, чем вы думаете
    </p>
    <Image src={TelegaIcon} alt="telegramm-icon" height={36} width={36}
      className="infinity-banner-tg" unoptimized />
    <Image src={LogoWhite} alt="southuub" width={220} height={24}
      className="infinity-banner-logo" unoptimized />
    <p className={`${FONT_MONT_BOOK.className} infinity-banner-text`}>
      подпишитесь, чтобы оставаться на связи
    </p>
  </div>
);

export const InfinityBanner = () => {
  const getLinkWithUtm = useGetLinkWithUtm();
  const trackRef = useRef<HTMLDivElement>(null);
  const animationRef = useRef<number>(0);
  const currentOffsetRef = useRef(0);
  const lastTimeRef = useRef(0);
  const isPausedRef = useRef(false);
  // Полоса стоит, пока её не видно, и начинает ехать, когда появляется на экране
  const isVisibleRef = useRef(false);

  const SPEED = 80;

  useEffect(() => {
    const track = trackRef.current;
    if (!track) return;

    const trackWidth = track.scrollWidth / 2;

    // стрелочная функция, а не function: в ней TypeScript помнит, что track не null
    const animate = (timestamp: number) => {
      if (!isPausedRef.current && isVisibleRef.current) {
        if (lastTimeRef.current === 0) {
          lastTimeRef.current = timestamp;
        }

        const delta = (timestamp - lastTimeRef.current) / 1000;
        currentOffsetRef.current += delta * SPEED;
        currentOffsetRef.current %= trackWidth;

        track.style.transform = `translateX(-${currentOffsetRef.current}px)`;
        lastTimeRef.current = timestamp;
      } else {
        lastTimeRef.current = 0;
      }

      animationRef.current = requestAnimationFrame(animate);
    };

    const start = () => {
      if (!animationRef.current) animationRef.current = requestAnimationFrame(animate);
    };
    const stop = () => {
      cancelAnimationFrame(animationRef.current);
      animationRef.current = 0;
      lastTimeRef.current = 0;
    };

    const observer = new IntersectionObserver(([entry]) => {
      isVisibleRef.current = entry.isIntersecting;
      if (entry.isIntersecting) start();
      else stop();
    });
    observer.observe(track);

    return () => {
      observer.disconnect();
      stop();
    };
  }, []);

  const handleMouseEnter = () => {
    isPausedRef.current = true;
  };

  const handleMouseLeave = () => {
    isPausedRef.current = false;
  };

  return (
    <a
      id="btn_lending_infinity_banner"
      className="infinity-banner-wrapper"
      href={getLinkWithUtm(TELEGRAM_CHANELL_LINK)}
      target="_blank"
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      <div className="infinity-banner-track">
        <div className="infinity-banner-items" ref={trackRef}>
          <Item />
          <Item />
          <Item />
          <Item />
          <Item />
          <Item />
          <Item />
          <Item />
        </div>
      </div>
    </a>
  );
};

// app/components/blocks/InfinityBanner.vue
<script setup lang="ts">
const pub = usePublicPath();
const getLinkWithUtm = useLinkWithUtm();
const { telegramChanellLink } = useRuntimeConfig().public;

const trackRef = ref<HTMLDivElement | null>(null);
let animationId = 0;
let currentOffset = 0;
let lastTime = 0;
let isPaused = false;
// Полоса стоит, пока её не видно, и начинает ехать, когда появляется на экране
let isVisible = false;

const SPEED = 80;

const TEXTS = ['Все инсайты и новости ближе, чем вы думаете', 'подпишитесь, чтобы оставаться на связи'];

const handleMouseEnter = () => {
    isPaused = true;
};

const handleMouseLeave = () => {
    isPaused = false;
};

let cleanup: (() => void) | undefined;

onMounted(() => {
    const track = trackRef.value;
    if (!track) return;

    const trackWidth = track.scrollWidth / 2;

    const animate = (timestamp: number) => {
        if (!isPaused && isVisible) {
            if (lastTime === 0) {
                lastTime = timestamp;
            }

            const delta = (timestamp - lastTime) / 1000;
            currentOffset += delta * SPEED;
            currentOffset %= trackWidth;

            track.style.transform = `translateX(-${currentOffset}px)`;
            lastTime = timestamp;
        } else {
            lastTime = 0;
        }

        animationId = requestAnimationFrame(animate);
    };

    const start = () => {
        if (!animationId) animationId = requestAnimationFrame(animate);
    };
    const stop = () => {
        cancelAnimationFrame(animationId);
        animationId = 0;
        lastTime = 0;
    };

    const observer = new IntersectionObserver(([entry]) => {
        isVisible = !!entry?.isIntersecting;
        if (isVisible) start();
        else stop();
    });
    observer.observe(track);

    cleanup = () => {
        observer.disconnect();
        stop();
    };
});

onBeforeUnmount(() => cleanup?.());
</script>

<template>
    <a
        id="btn_lending_infinity_banner"
        class="infinity-banner-wrapper"
        :href="getLinkWithUtm(telegramChanellLink)"
        target="_blank"
        @mouseenter="handleMouseEnter"
        @mouseleave="handleMouseLeave"
    >
        <div class="infinity-banner-track">
            <div ref="trackRef" class="infinity-banner-items">
                <div v-for="n in 8" :key="n" class="infinity-banner-item">
                    <template v-for="text in TEXTS" :key="text">
                        <img :src="pub('/v2/infinity-banner-tg.svg')" alt="telegramm-icon" height="36" width="36" loading="lazy" decoding="async" class="infinity-banner-tg">
                        <img :src="pub('/v2/header-logo-white.svg')" alt="southuub" width="220" height="24" loading="lazy" decoding="async" class="infinity-banner-logo">
                        <p :class="[FONT_MONT_BOOK, 'infinity-banner-text']">{{ text }}</p>
                    </template>
                </div>
            </div>
        </div>
    </a>
</template>
