// app/components/blocks/HowBecomeCommunityBlock.vue
<script setup lang="ts">
const lkLink = useLkProfileLink();

const handleClick = () => openExternal(lkLink('community'));

const title = 'стать частью\nсообщества';
const description = `мы заботливо формируем наше\nсообщество, чтобы вы в${NBSP}нём чувствовали\nсебя комфортно и${NBSP}усиливали друг друга. поэтому очень внимательно относимся\nк модерации каждой заявки.`;

let cleanup: (() => void) | undefined;

onMounted(() => {
    const header = document.querySelector('#header');
    const targetBlock = document.querySelector('#how-become-community-block');

    if (!header || !targetBlock) return;

    let lastScrollY = window.scrollY;
    let isHeaderBlack = false;

    const handleScroll = () => {
        const currentScrollY = window.scrollY;
        const blockTop = targetBlock.getBoundingClientRect().top;
        const isScrollingUp = currentScrollY < lastScrollY;

        if (blockTop <= 0) {
            if (!isHeaderBlack) {
                header.classList.add('header_black');
                isHeaderBlack = true;
            }
        } else if (isScrollingUp && blockTop <= 50) {
            if (!isHeaderBlack) {
                header.classList.add('header_black');
                isHeaderBlack = true;
            }
        } else if (isHeaderBlack) {
            header.classList.remove('header_black');
            isHeaderBlack = false;
        }

        lastScrollY = currentScrollY;
    };

    window.addEventListener('scroll', handleScroll);

    handleScroll();

    cleanup = () => window.removeEventListener('scroll', handleScroll);
});

onBeforeUnmount(() => cleanup?.());
</script>

<template>
    <div id="how-become-community-block" class="how-become-community-block-wrapper">
        <h3 :class="[FONT_MONT_BOOK, 'how-become-community-block-title']">{{ title }}</h3>

        <p :class="[FONT_MONT_BOOK, 'how-become-community-block-description']">{{ description }}</p>

        <AntButton
            id="btn_lending_apply_community"
            class="how-become-community-block-button base-button base-button_black"
            @click="handleClick"
        >
            <span :class="FONT_MONT_BOOK">подать заявку</span>
        </AntButton>
    </div>
</template>

// src/app/blocks/how-become-community-block/how-become-community-block.tsx
import { FONT_MONT_BOOK } from '../../fonts';

import './how-become-community-block.css';
import { AccesibleButton } from './how-become-community-block-button';
import { NBSP } from '@/app/constants';
import { useEffect } from 'react';

export const HowBecomeCommunityBlock = () => {
    useEffect(() => {
        const header = document.querySelector('#header');
        const targetBlock = document.querySelector('#how-become-community-block');
        
        if (!header || !targetBlock) return;

        let lastScrollY = window.scrollY;
        let isHeaderBlack = false;

        const handleScroll = () => {
            const currentScrollY = window.scrollY;
            const blockRect = targetBlock.getBoundingClientRect();
            const blockTop = blockRect.top;
            const isScrollingUp = currentScrollY < lastScrollY;
    
            if (blockTop <= 0) {
                if (!isHeaderBlack) {
                    header.classList.add('header_black');
                    isHeaderBlack = true;
                }
            } 
            else if (isScrollingUp && blockTop <= 50) {
                if (!isHeaderBlack) {
                    header.classList.add('header_black');
                    isHeaderBlack = true;
                }
            } else {
                if (isHeaderBlack) {
                    header.classList.remove('header_black');
                    isHeaderBlack = false;
                }
            }
        
            lastScrollY = currentScrollY;
        };

        window.addEventListener('scroll', handleScroll);
        
        handleScroll();

        return () => {
            window.removeEventListener('scroll', handleScroll);
        };
    }, []);

    return (
        <div className='how-become-community-block-wrapper' id='how-become-community-block'>
            <h3
                className={`${FONT_MONT_BOOK.className} how-become-community-block-title`}
            >
                {`стать частью\nсообщества`}
            </h3>

            <p
                className={`${FONT_MONT_BOOK.className} how-become-community-block-description`}
            >
                {`мы заботливо формируем наше\nсообщество, чтобы вы в${NBSP}нём чувствовали\nсебя комфортно и${NBSP}усиливали друг друга. поэтому очень внимательно относимся\nк модерации каждой заявки.`}
            </p>

            <AccesibleButton />
        </div>
    );
}
