// app/components/ui/ImageWithFallback.vue
<script setup lang="ts">
// Картинка с запасным файлом на случай ошибки загрузки
const props = defineProps<{
    src: string;
    altSrc: string;
    alt: string;
    width?: number | string;
    height?: number | string;
    sizes?: string;
    loading?: 'lazy' | 'eager';
}>();

const imgSrc = ref(props.src);
watch(() => props.src, (src) => { imgSrc.value = src; });
</script>

<template>
    <img
        :src="imgSrc"
        :alt="alt"
        :width="width"
        :height="height"
        :sizes="sizes"
        :loading="loading ?? 'lazy'"
        decoding="async"
        style="object-fit: cover;"
        @error="imgSrc = altSrc"
    >
</template>

// src/app/components/image-with-fallback/image-with-fallback.tsx
import { useState } from 'react';
import Image, { ImageProps, StaticImageData } from 'next/image';

type Props = ImageProps & {
  altSrc: string | StaticImageData;
  className?: string;
};

export const ImageWithFallback = ({ altSrc, className, ...options }: Props) => {
  const [imgSrc, setImgSrc] = useState(options.src);

  return (
    <Image
      src={imgSrc}
      alt={options.alt}
      width={options.width}
      height={options.height}
      sizes={options.sizes}
      loading={options.loading}
      onError={() => {
        setImgSrc(altSrc);
      }}
      className={className}
      style={{
        objectFit: 'cover'
      }}
    />
  );
}
